package com.cdot.onewire;

public enum OneWireError {
    NO_ERROR_SET(0),
    NO_DEVICES_ON_NET(1),
    RESET_FAILED(2),
    SEARCH_ERROR(3),
    ACCESS_FAILED(4),
    DS2480_NOT_DETECTED(5),
    DS2480_WRONG_BAUD(6),
    DS2480_BAD_RESPONSE(7),
    OPENCOM_FAILED(8),
    WRITECOM_FAILED(9),
    READCOM_FAILED(10),
    BLOCK_TOO_BIG(11),
    BLOCK_FAILED(12),
    PROGRAM_PULSE_FAILED(13),
    PROGRAM_BYTE_FAILED(14),
    WRITE_BYTE_FAILED(15),
    READ_BYTE_FAILED(16),
    WRITE_VERIFY_FAILED(17),
    READ_VERIFY_FAILED(18),
    WRITE_SCRATCHPAD_FAILED(19),
    COPY_SCRATCHPAD_FAILED(20),
    INCORRECT_CRC_LENGTH(21),
    CRC_FAILED(22),
    GET_SYSTEM_RESOURCE_FAILED(23),
    SYSTEM_RESOURCE_INIT_FAILED(24),
    DATA_TOO_LONG(25),
    READ_OUT_OF_RANGE(26),
    WRITE_OUT_OF_RANGE(27),
    DEVICE_SELECT_FAIL(28),
    READ_SCRATCHPAD_VERIFY(29),
    COPY_SCRATCHPAD_NOT_FOUND(30),
    ERASE_SCRATCHPAD_NOT_FOUND(31),
    ADDRESS_READ_BACK_FAILED(32),
    EXTRA_INFO_NOT_SUPPORTED(33),
    PG_PACKET_WITHOUT_EXTRA(34),
    PACKET_LENGTH_EXCEEDS_PAGE(35),
    INVALID_PACKET_LENGTH(36),
    NO_PROGRAM_PULSE(37),
    READ_ONLY(38),
    NOT_GENERAL_PURPOSE(39),
    READ_BACK_INCORRECT(40),
    INVALID_PAGE_NUMBER(41),
    CRC_NOT_SUPPORTED(42),
    CRC_EXTRA_INFO_NOT_SUPPORTED(43),
    READ_BACK_NOT_VALID(44),
    COULD_NOT_LOCK_REDIRECT(45),
    READ_STATUS_NOT_COMPLETE(46),
    PAGE_REDIRECTION_NOT_SUPPORTED(47),
    LOCK_REDIRECTION_NOT_SUPPORTED(48),
    READBACK_EPROM_FAILED(49),
    PAGE_LOCKED(50),
    LOCKING_REDIRECTED_PAGE_AGAIN(51),
    REDIRECTED_PAGE(52),
    PAGE_ALREADY_LOCKED(53),
    WRITE_PROTECTED(54),
    NONMATCHING_MAC(55),
    WRITE_PROTECT(56),
    WRITE_PROTECT_SECRET(57),
    COMPUTE_NEXT_SECRET(58),
    LOAD_FIRST_SECRET(59),
    POWER_NOT_AVAILABLE(60),
    XBAD_FILENAME(61),
    XUNABLE_TO_CREATE_DIR(62),
    REPEAT_FILE(63),
    DIRECTORY_NOT_EMPTY(64),
    WRONG_TYPE(65),
    BUFFER_TOO_SMALL(66),
    NOT_WRITE_ONCE(67),
    FILE_NOT_FOUND(68),
    OUT_OF_SPACE(69),
    TOO_LARGE_BITNUM(70),
    NO_PROGRAM_JOB(71),
    FUNC_NOT_SUP(72),
    HANDLE_NOT_USED(73),
    FILE_WRITE_ONLY(74),
    HANDLE_NOT_AVAIL(75),
    INVALID_DIRECTORY(76),
    HANDLE_NOT_EXIST(77),
    NONMATCHING_SNUM(78),
    NON_PROGRAM_PARTS(79),
    PROGRAM_WRITE_PROTECT(80),
    FILE_READ_ERR(81),
    ADDFILE_TERMINATED(82),
    READ_MEMORY_PAGE_FAILED(83),
    MATCH_SCRATCHPAD_FAILED(84),
    ERASE_SCRATCHPAD_FAILED(85),
    READ_SCRATCHPAD_FAILED(86),
    SHA_FUNCTION_FAILED(87),
    NO_COMPLETION_BYTE(88),
    WRITE_DATA_PAGE_FAILED(89),
    COPY_SECRET_FAILED(90),
    BIND_SECRET_FAILED(91),
    INSTALL_SECRET_FAILED(92),
    VERIFY_SIG_FAILED(93),
    SIGN_SERVICE_DATA_FAILED(94),
    VERIFY_AUTH_RESPONSE_FAILED(95),
    ANSWER_CHALLENGE_FAILED(96),
    CREATE_CHALLENGE_FAILED(97),
    BAD_SERVICE_DATA(98),
    SERVICE_DATA_NOT_UPDATED(99),
    CATASTROPHIC_SERVICE_FAILURE(100),
    LOAD_FIRST_SECRET_FAILED(101),
    MATCH_SERVICE_SIGNATURE_FAILED(102);

    private final int code;

    private final String[] strings = {
        /*000*/"No Error Was Set",
        /*001*/ "No Devices found on 1-Wire Network",
        /*002*/ "1-Wire Net Reset Failed",
        /*003*/ "Search ROM Error: Couldn't locate next device on 1-Wire",
        /*004*/ "Access Failed: Could not select device",
        /*005*/ "DS2480B Adapter Not Detected",
        /*006*/ "DS2480B: Wrong Baud",
        /*007*/ "DS2480B: Bad Response",
        /*008*/ "Open COM Failed",
        /*009*/ "Write COM Failed",
        /*010*/ "Read COM Failed",
        /*011*/ "Data Block Too Large",
        /*012*/ "Block Transfer failed",
        /*013*/ "Program Pulse Failed",
        /*014*/ "Program Byte Failed",
        /*015*/ "Write Byte Failed",
        /*016*/ "Read Byte Failed",
        /*017*/ "Write Verify Failed",
        /*018*/ "Read Verify Failed",
        /*019*/ "Write Scratchpad Failed",
        /*020*/ "Copy Scratchpad Failed",
        /*021*/ "Incorrect CRC Length",
        /*022*/ "CRC Failed",
        /*023*/ "Failed to acquire a necessary system resource",
        /*024*/ "Failed to initialize system resource",
        /*025*/ "Data too long to fit on specified device.",
        /*026*/ "Read exceeds memory bank end.",
        /*027*/ "Write exceeds memory bank end.",
        /*028*/ "Device select failed",
        /*029*/ "Read Scratch Pad verify failed.",
        /*030*/ "Copy scratchpad complete not found",
        /*031*/ "Erase scratchpad complete not found",
        /*032*/ "Address read back from scrachpad was incorrect",
        /*033*/ "Read page with extra-info not supported by this memory bank",
        /*034*/ "Read page packet with extra-info not supported by this memory bank",
        /*035*/ "Length of packet requested exceeds page size",
        /*036*/ "Invalid length in packet",
        /*037*/ "Program pulse required but not available",
        /*038*/ "Trying to access a read-only memory bank",
        /*039*/ "Current bank is not general purpose memory",
        /*040*/ "Read back from write compare is incorrect, page may be locked",
        /*041*/ "Invalid page number for this memory bank",
        /*042*/ "Read page with CRC not supported by this memory bank",
        /*043*/ "Read page with CRC and extra-info not supported by this memory bank",
        /*044*/ "Read back from write incorrect, could not lock page",
        /*045*/ "Read back from write incorrect, could not lock redirect byte",
        /*046*/ "The read of the status was not completed.",
        /*047*/ "Page redirection not supported by this memory bank",
        /*048*/ "Lock Page redirection not supported by this memory bank",
        /*049*/ "Read back byte on EPROM programming did not match.",
        /*050*/ "Can not write to a page that is locked.",
        /*051*/ "Can not lock a redirected page that has already been locked.",
        /*052*/ "Trying to redirect a locked redirected page.",
        /*053*/ "Trying to lock a page that is already locked.",
        /*054*/ "Trying to write to a memory bank that is write protected.",
        /*055*/ "Error due to not matching MAC.",
        /*056*/ "Memory Bank is write protected.",
        /*057*/ "Secret is write protected, can not Load First Secret.",
        /*058*/ "Error in Reading Scratchpad after Computing Next Secret.",
        /*059*/ "Load Error from Loading First Secret.",
        /*060*/ "Power delivery required but not available",
        /*061*/ "Not a valid file name.",
        /*062*/ "Unable to Create a Directory in this part.",
        /*063*/ "That file already exists.",
        /*064*/ "The directory is not empty.",
        /*065*/ "The wrong type of part for this operation.",
        /*066*/ "The max len for this file is too small.",
        /*067*/ "This is not a write once bank.",
        /*068*/ "The file can not be found.",
        /*069*/ "There is not enough space availabe.",
        /*070*/ "There is not a page to match that bit in the bitmap.",
        /*071*/ "There are no jobs for EPROM parts.",
        /*072*/ "Function not supported to modify attributes.",
        /*073*/ "Handle is not in use.",
        /*074*/ "Tring to read a write only file.",
        /*075*/ "There is no handle available for use.",
        /*076*/ "The directory provided is an invalid directory.",
        /*077*/ "Handle does not exist.",
        /*078*/ "Serial Number did not match with current job.",
        /*079*/ "Can not program EPROM because a non-EPROM part on the network.",
        /*080*/ "Write protect redirection byte is set.",
        /*081*/ "There is an inappropriate directory length.",
        /*082*/ "The file has already been terminated.",
        /*083*/ "Failed to read memory page of iButton part.",
        /*084*/ "Failed to match scratchpad of iButton part.",
        /*085*/ "Failed to erase scratchpad of iButton part.",
        /*086*/ "Failed to read scratchpad of iButton part.",
        /*087*/ "Failed to execute SHA function on SHA iButton.",
        /*088*/ "SHA iButton did not return a status completion byte.",
        /*089*/ "Write data page failed.",
        /*090*/ "Copy secret into secret memory pages failed.",
        /*091*/ "Bind unique secret to iButton failed.",
        /*092*/ "Could not install secret into user token.",
        /*093*/ "Transaction Incomplete: signature did not match.",
        /*094*/ "Transaction Incomplete: could not sign service data.",
        /*095*/ "User token did not provide a valid authentication response.",
        /*096*/ "Failed to answer a challenge on the user token.",
        /*097*/ "Failed to create a challenge on the coprocessor.",
        /*098*/ "Transaction Incomplete: service data was not valid.",
        /*099*/ "Transaction Incomplete: service data was not updated.",
        /*100*/ "Unrecoverable, catastrophic service failure occurred.",
        /*101*/ "Load First Secret from scratchpad data failed.",
        /*102*/ "Failed to match signature of user's service data."
    };

    private OneWireError(int code) {

        this.code = code;
    }

    public String text() {
        return strings[code];
    }
};
